### ISSUE TITLE
Bug downloading cbioportal 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/pgdb#2]
Error executing process > 'cbioportal_proteindb'

Caused by:
  Process `cbioportal_proteindb` terminated with an error exit status (1)

Command executed:

  pypgatk_cli.py cbioportal-to-proteindb --config_file "/home/yperez/.nextflow/assets/bigbio/pgdb/configs/cbioportal_config.yaml" --input_mutation cbioportal_allstudies_data_mutations_mskcc.txt --input_cds Homo_sapiens.GRCh37.75.cds.all.fa --clinical_sample_file cbioportal_allstudies_data_clinical_sample.txt --tissue_type all  --output_db cbioPortal_proteinDB.fa

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/usr/local/bin/pypgatk_cli.py", line 4, in <module>
      __import__('pkg_resources').run_script('pypgatk==0.0.5', 'pypgatk_cli.py')
    File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in run_script
      self.require(requires)[0].run_script(script_name, ns)
    File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1446, in run_script
      exec(code, namespace, namespace)
    File "/usr/local/lib/python3.7/dist-packages/pypgatk-0.0.5-py3.7.egg/EGG-INFO/scripts/pypgatk_cli.py", line 43, in <module>
      cli()
    File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
      return self.main(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
      rv = self.invoke(ctx)
    File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
      return callback(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 17, in new_func
      return f(get_current_context(), *args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/pypgatk-0.0.5-py3.7.egg/pypgatk/commands/cbioportal_to_proteindb.py", line 31, in cbioportal_to_proteindb
      cosmic_to_proteindb_service = CancerGenomesService(config_file, pipeline_arguments)
    File "/usr/local/lib/python3.7/dist-packages/pypgatk-0.0.5-py3.7.egg/pypgatk/cgenomes/cgenomes_proteindb.py", line 26, in __init__
      super(CancerGenomesService, self).__init__(self.CONFIG_COSMIC_DATA, config_file, pipeline_arguments)
    File "/usr/local/lib/python3.7/dist-packages/pypgatk-0.0.5-py3.7.egg/pypgatk/toolbox/general.py", line 50, in __init__
      with open(yaml_configuration_file, 'r') as f:
  FileNotFoundError: [Errno 2] No such file or directory: '/home/yperez/.nextflow/assets/bigbio/pgdb/configs/cbioportal_config.yaml'

Work dir:
  /home/yperez/ms-work/proteogenomics-project/work/0e/3c333dd82854e49ac4acc869a24b33

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

**Comment by husensofteng** [comment]
It says that it can't find the cbioportal configuration file. Can you make sure [this file](https://github.com/bigbio/pgdb/blob/master/configs/cbioportal_config.yaml) does exist on /home/yperez/.nextflow/assets/bigbio/pgdb/configs/cbioportal_config.yaml ?

**Comment by ypriverol** [comment]
I check and it exists. It is really a strange error.

**Comment by husensofteng** [comment]
indeed, I will run it locally tonight and will see.

**Comment by husensofteng** [comment]
Fixed. 
the config file was directly given to the script-command without marking it as input in the process. the same thing was done to the cosmic process.
